//------------------------------------------------------------------------------
// <auto-generated>
//     Strongly-typed accessor for the AppResources.resx string table.
//     Hand-maintained (no VS designer dependency). Keep keys in sync with the .resx files.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member (generated accessor)

namespace JesusTheChrist.Presentation.Resources;

using System.Globalization;
using System.Resources;

/// <summary>
/// Strongly-typed access to localized UI strings.
/// </summary>
public static class AppResources
{
    private static readonly ResourceManager ResourceManagerInstance =
        new ResourceManager("JesusTheChrist.Presentation.Resources.AppResources", typeof(AppResources).Assembly);

    private static CultureInfo? cultureOverride;

    /// <summary>
    /// Gets or sets the culture used for resource lookups. When null, the current UI culture is used.
    /// </summary>
    public static CultureInfo? Culture
    {
        get => cultureOverride;
        set => cultureOverride = value;
    }

    public static string AppTitle => Get("AppTitle");

    public static string NavHome => Get("NavHome");

    public static string SettingsTitle => Get("SettingsTitle");

    public static string SettingsReadingFontSize => Get("SettingsReadingFontSize");

    public static string SettingsFontSample => Get("SettingsFontSample");

    public static string SettingsTheme => Get("SettingsTheme");

    public static string ThemeSystem => Get("ThemeSystem");

    public static string ThemeLight => Get("ThemeLight");

    public static string ThemeDark => Get("ThemeDark");

    public static string SettingsLanguage => Get("SettingsLanguage");

    public static string LanguageEnglish => Get("LanguageEnglish");

    public static string LanguageSpanish => Get("LanguageSpanish");

    public static string SettingsLanguageNote => Get("SettingsLanguageNote");

    public static string SettingsTrackStreak => Get("SettingsTrackStreak");

    public static string SettingsStreakHint => Get("SettingsStreakHint");

    public static string SettingsAbout => Get("SettingsAbout");

    public static string SettingsAttribution => Get("SettingsAttribution");

    public static string SettingsReadInvitation => Get("SettingsReadInvitation");

    public static string NoteTitle => Get("NoteTitle");

    public static string NotePlaceholder => Get("NotePlaceholder");

    public static string ActionDelete => Get("ActionDelete");

    public static string ActionSave => Get("ActionSave");

    public static string InvitationTitle => Get("InvitationTitle");

    public static string ActionBegin => Get("ActionBegin");

    public static string CardAddNote => Get("CardAddNote");

    public static string CardEditNote => Get("CardEditNote");

    public static string CardShowContext => Get("CardShowContext");

    public static string CardHideContext => Get("CardHideContext");

    public static string A11yExpandCollapse => Get("A11yExpandCollapse");

    public static string A11yToggleRead => Get("A11yToggleRead");

    public static string A11yRead => Get("A11yRead");

    public static string HomeReferencesReadFormat => Get("HomeReferencesReadFormat");

    private static string Get(string name) =>
        ResourceManagerInstance.GetString(name, cultureOverride) ?? string.Empty;
}
