#!/usr/bin/env bash
#
# collect-secrets.sh — gather the Google Play release secrets from their local
# locations into ./.env (gitignored). Secret VALUES are never printed.
#
# Pair with push-secrets.sh, which uploads them to GitHub Actions secrets so the
# tag-triggered release workflow (.github/workflows/release.yml) can build + sign
# + upload the .aab. See docs/android/HOW-TO-DEPLOY.md.
#
# Sources (override via environment, or edit the defaults below):
#   JTC_KEYSTORE                   path to the upload keystore
#   JTC_KEYSTORE_PASS              the keystore store/key password
#   PLAY_SERVICE_ACCOUNT_JSON_FILE path to the Play service-account JSON key
#
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$REPO_ROOT/.env"

KEYSTORE_PATH="${JTC_KEYSTORE:-$HOME/keys/vozloop-upload.keystore}"
KEYSTORE_PASSWORD="${JTC_KEYSTORE_PASS:-}"
SERVICE_ACCOUNT_JSON="${PLAY_SERVICE_ACCOUNT_JSON_FILE:-}"

fail() { echo "ERROR: $*" >&2; exit 1; }

[ -f "$KEYSTORE_PATH" ] || fail "keystore not found at '$KEYSTORE_PATH' (set JTC_KEYSTORE)."
[ -n "$KEYSTORE_PASSWORD" ] || fail "keystore password not set (export JTC_KEYSTORE_PASS)."
[ -n "$SERVICE_ACCOUNT_JSON" ] || fail "service-account JSON path not set (export PLAY_SERVICE_ACCOUNT_JSON_FILE=/path/to/key.json)."
[ -f "$SERVICE_ACCOUNT_JSON" ] || fail "service-account JSON not found at '$SERVICE_ACCOUNT_JSON'."

# Make the .env owner-only before writing any secrets into it.
umask 077

{
  echo "# Generated by scripts/collect-secrets.sh — secrets, DO NOT COMMIT (gitignored)."
  echo "PLAY_KEYSTORE_BASE64=$(base64 -w0 "$KEYSTORE_PATH")"
  echo "PLAY_KEYSTORE_PASSWORD=$KEYSTORE_PASSWORD"
  echo "PLAY_SERVICE_ACCOUNT_JSON_BASE64=$(base64 -w0 "$SERVICE_ACCOUNT_JSON")"
} > "$ENV_FILE"

echo "Wrote 3 secrets to $ENV_FILE (values not shown). Next: scripts/push-secrets.sh"
